internal:
  error-encountered: 'An unknown error has occurred: {0}'
