internal:
  error-encountered: "Une erreur inconnue s'est produite : {0}"
