internal:
  error-encountered: 不明なエラーが発生しました：{0}
