internal:
  error-encountered: 发生未知错误：{0}
