internal:
  error-encountered: 出現未知錯誤：{0}
